// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulacionBackend.Data;

#nullable disable

namespace SimulacionBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528185345_AgregandoColasYEficiencia")]
    partial class AgregandoColasYEficiencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SimulacionBackend.Data.SimulacionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EficienciaDesmantelamiento")
                        .HasColumnType("REAL");

                    b.Property<double>("EficienciaReacondicionamiento")
                        .HasColumnType("REAL");

                    b.Property<double>("EficienciaTriage")
                        .HasColumnType("REAL");

                    b.Property<int>("EquiposDesmantelados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquiposEnColaDesmantelamiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquiposEnColaReacondicionamiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquiposEnColaTriage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquiposReacondicionados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("TEXT");

                    b.Property<double>("KilosMetalRecuperado")
                        .HasColumnType("REAL");

                    b.Property<double>("KilosPlasticoRecuperado")
                        .HasColumnType("REAL");

                    b.Property<double>("TiempoPromedioEspera")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalEquiposIngresados")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Simulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
